### ISSUE TITLE
Error raised if no request_types are configured

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/arclight#692]
In a `repositories.yml` file, if no request_types are configured an error will be raised.

I think this was introduced in #674 

```
ActionView::Template::Error: undefined local variable or method `request_types' for #<Arclight::Repository:0x...> Did you mean? request_url_for_type
```

**Comment by billdueber** [comment]
@mejackreed Any memory of how you triggered this? I'm having trouble reproducing.

**Comment by mejackreed** [comment]
@billdueber if `request_types` keys are not present in `repositories.yml` the error will be triggered

**Comment by billdueber** [comment]
No, I understand the error, but I can't make it happen.  I've tried messing with the app and of course running the tests and I can't break it in this way.

**Comment by mejackreed** [comment]
Gotcha.. try removing `request_types:` keys from `.internal_test_app/config/repositories.yml`

**Comment by billdueber** [comment]
Well, now I feel dumb. I had an old server hanging on that was getting all my requests. 

PR coming now.
