### ISSUE TITLE
Missing Document Actions Method on fresh install of v1.0.0.beta3

### ISSUE THREAD

**Issue by lfarrell** [projectblacklight/arclight#1413]
Doing a fresh install of the latest arclight beta, with ruby 3.0.2, results in an `undefined method `document_actions' for Arclight::HeaderComponent:Class` error.

<img width="1099" alt="Screen Shot 2023-03-02 at 1 12 36 PM" src="https://user-images.githubusercontent.com/436691/222516891-68d83265-7964-460a-8a37-42807cb87b90.png">

If I comment out lines 50-52 of catalog_controller.rb, and then reload I then get the following error `undefined method `collection_actions' `
<img width="1377" alt="Screen Shot 2023-03-02 at 1 21 50 PM" src="https://user-images.githubusercontent.com/436691/222518021-b6b651fc-a826-4740-99f3-39f2cf88e502.png">

**Comment by archivalGrysbok** [comment]
I'm seeing this, took. I also saw it on v1.0.0.beta2.

```
arclight@truman:~/arclightBeta$ bin/rails s
=> Booting Puma
=> Rails 7.0.4.2 application starting in development 
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.6.5 (ruby 3.0.2-p107) ("Birdie's Version")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 1382374
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop
Started GET "/" for 127.0.0.1 at 2023-03-06 11:53:54 -0500
  ActiveRecord::SchemaMigration Pluck (0.2ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by Arclight::RepositoriesController#index as HTML
Completed 500 Internal Server Error in 77ms (ActiveRecord: 0.0ms | Allocations: 33953)


  
NoMethodError (undefined method `document_actions' for Arclight::HeaderComponent:Class):
  
app/controllers/catalog_controller.rb:51:in `block in <class:CatalogController>'
app/controllers/catalog_controller.rb:8:in `<class:CatalogController>'
app/controllers/catalog_controller.rb:4:in `<main>'

```

**Comment by jcoyne** [comment]
@archivalGrysbok What is on line 51 of your app/controllers/catalog_controller.rb?

**Comment by archivalGrysbok** [comment]
lines 50-52:

    config.header_component = Arclight::HeaderComponent
*    config.add_results_document_tool(:online, component:
Arclight::OnlineStatusIndicatorComponent)*
    config.add_results_document_tool(:arclight_bookmark_control, component:
Arclight::BookmarkComponent)

**Comment by archivalGrysbok** [comment]
starting in production mode:

`=> Booting Puma
=> Rails 7.0.4.2 application starting in production 
=> Run `bin/rails server --help` for more startup options
Exiting
/home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/blacklight-8.0.0.beta8/lib/blacklight/configuration.rb:552:in `add_results_document_tool': undefined method `document_actions' for Arclight::HeaderComponent:Class (NoMethodError)
	from /home/arclight/arclightBeta/app/controllers/catalog_controller.rb:52:in `block in <class:CatalogController>'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/blacklight-8.0.0.beta8/lib/blacklight/configuration.rb:398:in `configure'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/blacklight-8.0.0.beta8/app/models/concerns/blacklight/configurable.rb:37:in `configure_blacklight'
	from /home/arclight/arclightBeta/app/controllers/catalog_controller.rb:9:in `<class:CatalogController>'
	from /home/arclight/arclightBeta/app/controllers/catalog_controller.rb:4:in `<main>'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:30:in `require'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:135:in `cget'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:25:in `each'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:25:in `ls'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:16:in `each'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:297:in `block in eager_load_all'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:295:in `each'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:295:in `eager_load_all'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/application/finisher.rb:74:in `block in <module:Finisher>'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/initializable.rb:32:in `instance_exec'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/initializable.rb:32:in `run'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
	from /usr/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/lib/ruby/3.0.0/tsort.rb:347:in `each'
	from /usr/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /usr/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
	from /usr/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/initializable.rb:60:in `run_initializers'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/application.rb:372:in `initialize!'
	from /home/arclight/arclightBeta/config/environment.rb:5:in `<main>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/rack-2.2.6.3/lib/rack/builder.rb:116:in `eval'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/rack-2.2.6.3/lib/rack/builder.rb:116:in `new_from_string'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/rack-2.2.6.3/lib/rack/builder.rb:105:in `load_file'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/rack-2.2.6.3/lib/rack/builder.rb:66:in `parse_file'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/rack-2.2.6.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/rack-2.2.6.3/lib/rack/server.rb:249:in `app'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/rack-2.2.6.3/lib/rack/server.rb:422:in `wrapped_app'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/rack-2.2.6.3/lib/rack/server.rb:312:in `block in start'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/rack-2.2.6.3/lib/rack/server.rb:379:in `handle_profiling'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/rack-2.2.6.3/lib/rack/server.rb:311:in `start'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/commands/server/server_command.rb:38:in `start'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/commands/server/server_command.rb:143:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/command/base.rb:87:in `perform'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/command.rb:48:in `invoke'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.2/lib/rails/commands.rb:18:in `<main>'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/arclight/arclightBeta/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:4:in `<main>'`

**Comment by archivalGrysbok** [comment]
Hmm. I updated my Gemfile and still saw it with arclight 1.0.0.beta4 and blacklight 8.0.0.
Then I deleted the whole project folder and reinstalled. I still saw it. 

I used these steps: 

1. rails new arclightBeta4
2. cd arclightBeta4
3. bundle add arclight -v 1.0.0.beta4
4. bundle exec rails g blacklight:install --devise
5. bundle exec rails g arclight:install -f
6. bundle exec rake db:migrate

Started in development using `bundle exec rails s`

```
arclight@truman:~/arclightBeta4$ bundle exec rails s
=> Booting Puma
=> Rails 7.0.4.3 application starting in development 
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.6.5 (ruby 3.0.2-p107) ("Birdie's Version")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 2947872
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop

Started GET "/" for 127.0.0.1 at 2023-03-20 12:56:35 -0400
  ActiveRecord::SchemaMigration Pluck (0.2ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by Arclight::RepositoriesController#index as HTML
Completed 500 Internal Server Error in 44ms (ActiveRecord: 0.0ms | Allocations: 32980)


  
NoMethodError (undefined method `document_actions' for Arclight::HeaderComponent:Class):
  
app/controllers/catalog_controller.rb:51:in `block in <class:CatalogController>'
app/controllers/catalog_controller.rb:8:in `<class:CatalogController>'
app/controllers/catalog_controller.rb:4:in `<main>'

```
Screenshot:

![image](https://user-images.githubusercontent.com/370099/226412966-39d9c906-da42-4a35-87b9-32c59bfb8906.png)

**Comment by jcoyne** [comment]
Okay, that's exactly the same steps I took and it worked for me (of course). The only difference I can see if you are on ruby 3.0 and I'm using 3.1.3

**Comment by archivalGrysbok** [comment]
I'm on 3.0.2 right now, so I'll bump up to 3.1.3 and see if that's the magic.

**Comment by lfarrell** [comment]
I got the same results as @archivalGrysbok using ruby 3.0.2. Due to our local infrastructure we can't currently go past Ruby 3.0.2.

**Comment by jcoyne** [comment]
Thank you for testing that.  It's nice to at least have some idea of where things go sideways.

**Comment by lfarrell** [comment]
I got it to work on my laptop by using 3.1.3 as well. So, seconding @archivalGrysbok, it seems something somewhere is valid in 3.1, but not 3.0.

**Comment by lfarrell** [comment]
I suspect it's the use of this syntax for arguements`def initialize(presenter:, download_component:)` in a number of components, which is valid in 3.1, but not 3.0.
From the ruby 3.1 release guide https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/
```
Values in Hash literals and keyword arguments can be omitted. [[Feature #14579]](https://bugs.ruby-lang.org/issues/14579)

    {x:, y:} is syntax sugar for {x: x, y: y}.
    foo(x:, y:) is syntax sugar for foo(x: x, y: y).
```

**Comment by jcoyne** [comment]
> I suspect it's the use of this syntax for arguements def initialize(presenter:, download_component:) in a number of components, which is valid in 3.1, but not 3.0.

@lfarrell I think you misunderstand the change.  It is only to method calls, not to method definitions.  This is valid in Ruby 2.7 and indicates that the arguments are required:
```ruby
 def initialize(presenter:, download_component:)
 ```

**Comment by jcoyne** [comment]
I don't think we have the capacity to fix this in Arclight. While we can support ruby 3.0, we can only support the latest patch level release, which is currently 3.0.5 (although it looks like 3.0.3-4 are probably fine too).
